//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn_mvc.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student
    {
        public int StdId { get; set; }
        public string StdName { get; set; }
        public string StdRollNumber { get; set; }
        public string StdClass { get; set; }
        public string StdSubject { get; set; }
    }
}
