//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn_mvc.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_email { get; set; }
        public string emp_phone { get; set; }
        public string emp_address { get; set; }
        public string emp_city { get; set; }
        public string emp_state { get; set; }
        public string emp_country { get; set; }
    }
}
