//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn_mvc.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_company
    {
        public int cmp_id { get; set; }
        public string cmp_name { get; set; }
        public string cmp_address { get; set; }
        public Nullable<int> cmp_rating { get; set; }
    }
}
